export const PHARMACY_APPROVAL_REQUEST = "PHARMACY_APPROVAL_REQUEST";
export const PHARMACY_APPROVAL_SUCCESS = "PHARMACY_APPROVAL_SUCCESS";
export const PHARMACY_APPROVAL_FAIL = "PHARMACY_APPROVAL_FAIL";

export const MEDICINE_APPROVAL_REQUEST = "MEDICINE_APPROVAL_REQUEST";
export const MEDICINE_APPROVAL_SUCCESS = "MEDICINE_APPROVAL_SUCCESS";
export const MEDICINE_APPROVAL_FAIL = "MEDICINE_APPROVAL_FAIL";

export const ADMIN_GET_ALL_MEDICINES_REQUEST = "ADMIN_GET_ALL_MEDICINES_REQUEST";
export const ADMIN_GET_ALL_MEDICINES_SUCCESS = "ADMIN_GET_ALL_MEDICINES_SUCCESS";
export const ADMIN_GET_ALL_MEDICINES_FAIL = "ADMIN_GET_ALL_MEDICINES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
