export const CUSTOMER_ORDER_REQUEST = "CUSTOMER_ORDER_REQUEST";
export const CUSTOMER_ORDER_SUCCESS = "CUSTOMER_ORDER_SUCCESS";
export const CUSTOMER_ORDER_FAIL = "CUSTOMER_ORDER_FAIL";

export const CUSTOMER_ORDER_DETAILS_REQUEST = "CUSTOMER_ORDER_DETAILS_REQUEST";
export const CUSTOMER_ORDER_DETAILS_SUCCESS = "CUSTOMER_ORDER_DETAILS_SUCCESS";
export const CUSTOMER_ORDER_DETAILS_FAIL = "CUSTOMER_ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
