export const REQUEST_PHARMACY_REQUEST = "REQUEST_PHARMACY_REQUEST";
export const REQUEST_PHARMACY_SUCCESS = "REQUEST_PHARMACY_SUCCESS";
export const REQUEST_PHARMACY_FAIL = "REQUEST_PHARMACY_FAIL";
export const RESET_PHARMACY_REQUEST_SUCCESS = "RESET_PHARMACY_REQUEST_SUCCESS";

export const REQUEST_MEDICINE_REQUEST = "REQUEST_MEDICINE_REQUEST";
export const REQUEST_MEDICINE_SUCCESS = "REQUEST_MEDICINE_SUCCESS";
export const REQUEST_MEDICINE_FAIL = "REQUEST_MEDICINE_FAIL";
export const RESET_MEDICINE_REQUEST_SUCCESS = "RESET_MEDICINE_REQUEST_SUCCESS";

export const PHARMACY_REQUEST = "PHARMACY_REQUEST";
export const PHARMACY_SUCCESS = "PHARMACY_SUCCESS";	
export const PHARMACY_FAIL = "PHARMACY_FAIL";

export const OWNER_SPECIFIC_PHARMACY_ORDER_REQUEST = "OWNER_SPECIFIC_ORDER_REQUEST";
export const OWNER_SPECIFIC_PHARMACY_ORDER_SUCCESS = "OWNER_SPECIFIC_ORDER_SUCCESS";
export const OWNER_SPECIFIC_PHARMACY_ORDER_FAIL = "OWNER_SPECIFIC_ORDER_FAIL";

export const OWNER_ORDER_DETAILS_REQUEST = "OWNER_ORDER_DETAILS_REQUEST";
export const OWNER_ORDER_DETAILS_SUCCESS = "OWNER_ORDER_DETAILS_SUCCESS";
export const OWNER_ORDER_DETAILS_FAIL = "OWNER_ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
