export const ALL_PHARMACY_REQUEST = "ALL_PHARMACY_REQUEST";
export const ALL_PHARMACY_SUCCESS = "ALL_PHARMACY_SUCCESS";
export const ALL_PHARMACY_FAIL = "ALL_PHARMACY_FAIL";

export const PHARMACY_DETAILS_REQUEST = "PHARMACY_DETAILS_REQUEST";
export const PHARMACY_DETAILS_SUCCESS = "PHARMACY_DETAILS_SUCCESS";
export const PHARMACY_DETAILS_FAIL = "PHARMACY_DETAILS_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
